version: '3'

services:
  # フロントエンド（React + TypeScript）
  frontend:
    image: node:18-alpine
    container_name: event_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:5173"
    command: sh -c "npm run dev -- --host 0.0.0.0 || (npm install && npm run dev -- --host 0.0.0.0)"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  # バックエンド（Laravel + PHP）
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: event_backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=eventdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # データベース（PostgreSQL）
  db:
    image: postgres:14-alpine
    container_name: event_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=eventdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # Webサーバー（Nginx）
  nginx:
    image: nginx:alpine
    container_name: event_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
    depends_on:
      - backend
      - frontend

  # キャッシュ（Redis）
  redis:
    image: redis:alpine
    container_name: event_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: